services:
  postgres:
    image: postgres:16-alpine
    container_name: task-time-tracker-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: task_tracker
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_user -d task_tracker"]
      interval: 5s
      timeout: 3s
      retries: 10

#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: task-time-tracker-api
#    restart: unless-stopped
#    depends_on:
#      postgres:
#        condition: service_healthy
#    environment:
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_NAME: task_tracker
#      DB_USER: task_user
#      DB_PASSWORD: task_password
#      JWT_SECRET: TjXU+N1Dadpod09PQWEyzDYlVTVZgeA4K5tA+Yd2X9LnoYMVlJnTfsTKtcSnP9gJ
#      JWT_EXPIRATION_MS: 3600000
#    ports:
#      - "8080:8080"

volumes:
  postgres_data:
